template header

ruleSeq
eventType
rules
ruleId
subrules
item
groupId


import java.util.ArrayList;
import com.alibaba.fastjson.JSONObject;


template "rulesengine-filter"

rule "transpond_@{ruleSeq}"
/*
all condition elements be evaluated by agenda when rules fired ,even if the first condtion element is false,so add agenda-group.
only activate id's group
*/
agenda-group "@{groupId}"
salience @{ruleId}
when
	Topic(ruleIdList contains @{ruleId} );
	$json : JSONObject(@{rules});
	$proxy :RuleProxy();
	$remain : ArrayList( size >= 1)
		from collect( JSONObject(@{subrules} ) from $json.getJSONArray("@{item}"));
then
	Action action = new Action();
    action.transpond($json,$remain,$proxy,"@{item}",@{ruleId},1);

end

rule "filter_@{ruleSeq}"
agenda-group "@{groupId}"
salience @{ruleId}
when
	Topic(ruleIdList contains @{ruleId} );
	$json : JSONObject(@{rules});
	$proxy :RuleProxy();
	$remain : ArrayList( size >= 1)
		from collect( JSONObject( !(@{subrules})) from $json.getJSONArray("@{item}"));
then
	Action action = new Action();
    action.transpond($json,$remain,$proxy,"@{item}",@{ruleId},2);

end
end template